name: Publish D&D Homebrew

on:
  push:
    branches:
      - main
      - autodeploy
    paths:
      - "src/shared/**"
      - "src/campaigns/**"

jobs:
  detect:
    runs-on: ubuntu-latest

    outputs:
      campaigns: ${{ steps.changed.outputs.campaigns }}

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - id: changed
        name: "Detect changed files"
        run: |
          CAMPAIGNS=""

          while IFS= read -r FILE
          do
            if [[ "$FILE" =~ ^src/campaigns/([^/]+)/ ]]; then
              CAMP="${BASH_REMATCH[1]}"
              if [[ -z "$CAMPAIGNS" ]]; then
                CAMPAIGNS="$CAMP"
              else
                CAMPAIGNS="$CAMPAIGNS,$CAMP"
              fi
            fi

            if [[ "$FILE" =~ ^src/shared/ ]]; then
              CAMPAIGNS="ALL"
            fi
          done < <(git diff --name-only HEAD^ HEAD)

          if [ "$CAMPAIGNS" = "ALL" ]; then
            CAMPAIGNS=$(ls src/campaigns | jq -R -s -c 'split("\n")[:-1]')
          else
            CAMPAIGNS=$(echo "$CAMPAIGNS" | tr ',' '\n' | sort -u | jq -R -s -c 'split("\n")[:-1]')
          fi

          echo "campaigns=$CAMPAIGNS" >> $GITHUB_OUTPUT

  build:
    needs: detect

    environment:
      name: production

    strategy:
      matrix:
        campaign: ${{ fromJson(needs.detect.outputs.campaigns) }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - run: echo ${{ matrix.campaign }}

      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm ci

      - run: npm link

      - run: npm run build "${{ matrix.campaign }}"

      - uses: actions/upload-pages-artifact@v5
        with:
          path: builds

      - uses: actions/deploy-pages@v5
