name: Publish D&D Homebrew

on:
  push:
    branches:
      - main
      - autodeploy
    paths:
      - "src/shared/**"
      - "src/campaigns/**"

jobs:
  detect:
    runs-on: ubuntu-latest

    outputs:
      campaigns: ${{ steps.changed.outputs.campaigns }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: changed
        run: |
          CAMPAIGNS=""

          git diff --name-only HEAD^ HEAD | while IFS= read -r FILE
          do
            echo "$FILE"
            if [[ "$FILE" =~ ^src/campaigns/([^/]+)/ ]]; then
              echo "ecco CAMPAIGN"
              echo "${BASH_REMATCH[1]}"
              echo "$CAMPAIGNS"
              CAMPAIGNS="$CAMPAIGNS,${BASH_REMATCH[1]}"
            fi

            if [[ "$FILE" =~ ^src/shared/ ]]; then
              echo "ecco SHARED"
              CAMPAIGNS="ALL"
            fi
          done

          echo "-------------"
          echo "$CAMPAIGNS"

          if [ "$CAMPAIGNS" = "ALL" ]; then
            echo "ecco ALL"
            CAMPAIGNS=$(ls src/campaigns | jq -R -s -c 'split("\n")[:-1]')
          else
            echo "-------------"
            echo "$CAMPAIGNS"
            echo "$CAMPAIGNS" | tr ',' ' uuuu '
            echo "$CAMPAIGNS" | tr ',' '\n'
            echo "$CAMPAIGNS" | jq -R -s -c 'split(",")[:-1]'
            echo "$CAMPAIGNS" | tr ',' '\n' | jq -R -s -c 'split("\n")[:-1]'
            CAMPAIGNS=$(echo "$CAMPAIGNS" | tr ',' '\n' | jq -R -s -c 'split("\n")[:-1]')
          fi

          echo "-----------------"
          echo "$CAMPAIGNS"

          echo "campaigns=$CAMPAIGNS" >> $GITHUB_OUTPUT

  build:
    needs: detect

    strategy:
      matrix:
        campaign: ${{ fromJson(needs.detect.outputs.campaigns) }}

    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ matrix.campaign }}

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm ci

      - run: npx build-campaigns "${{ matrix.campaign }}"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: builds

      - uses: actions/deploy-pages@v4
